config/routes.rb
Photo::Application.routes.draw do
  resources :images

  resources :albums

  resources :pictures
  
end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :album
	mount_uploader :image, ImageUploaderUploader
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@albums = Album.all
   
	end

	def new
		@album = Album.new
	end

	def show
		@album = Album.find(params[:id])
	end

	def create
    @album = Album.create create_album_params
    redirect_to albums_path
  end

  def edit
  	@album = Album.find params[:id]
  end

 	def update
  	@album = Album.find params[:id]
  	@album.update_attributes create_album_params
  	redirect_to albums_path
  end

  def destroy
  	@album = Album.find(params[:id])
  	@album.delete
  	redirect_to albums_path
  end

  private

  def set_prod
    @album = Album.find(params[:id])
  end

  private

  def create_album_params
  	params.require(:album).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    
    @image = Image.new(:album_id => params[:album_id])
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
   
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :image)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.all
	end

	def new
		@picture = Picture.new
	end

	def show
		@picture = Picture.find(params[:id])
	end


	def create
    @picture = Picture.create create_picture_params
    redirect_to pictures_path
	end

	private

	def create_picture_params
  	params.require(:picture).permit(:title, :image)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@album) do |f| %>
	<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

<%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', album_path %>

app/views/albums/index.html.erb
<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
  <% @albums.each do |album| %>
 <%= album.name %>
 <% album.images.each do |image| %> 
   <%= image_tag image.image_url %>
 <% end %>
<% end %>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
      </td>

        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

<% for album in @albums %>
  <div class="gallery">
    <h2><%= link_to album.name, album %></h2>
    
  </div>
<% end %>

<p><%= link_to "New Gallery", new_album_path %></p>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= form_for(@album) do |f| %>
	<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
 		<%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <strong>Album:</strong>
  <%= @album.name %>
</p>
<% for album in @album.images %>
<p>
  <strong>Album:</strong>
  <%= @album.image %>
</p
<% end %>


<%= link_to 'Edit', edit_album_path(@album) %> 
<%= link_to 'Back', albums_path %>

<div id="paintings">
  <% for album in @album.images %>
    <div class="painting">
      <%= image_tag image.image_url(:thumb) if image.image? %>
      <div class="name"><%= image.name %></div>
      <div class="actions">
        
        <%= link_to "remove", image, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>
  <%= link_to "Add a Painting", new_image_path(:album_id => @image) %> |
  <%= link_to "Remove Gallery", @album, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Galleries", images_path %>
</p>

app/views/images/_form.html.erb
<%= form_for @image, html: { multipart: true } do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>



<p>
  <strong>Image:</strong>
 <%= image_tag @image.image_url %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<h1>Index Pictures<h1>

<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.image %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paint', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New album</h1>
<%= form_for @picture, html: { multipart: true } do |f| %>

	<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </p>

   <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', albums_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Album:</strong>
  <%= @picture.title %>
</p>
<p>
  <strong>Album:</strong>
  <%= @picture.image %>
</p
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>